/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ATra
 */
public class CipherPanel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CipherPanel.class.getName());

    /**
     * Creates new form CipherPanel
     */
    public CipherPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLbl = new javax.swing.JLabel();
        InputTxtField = new javax.swing.JTextField();
        InputLbl = new javax.swing.JLabel();
        EncryptBtn = new javax.swing.JButton();
        DecryptBtn = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        KeyLbl = new javax.swing.JLabel();
        OutputTxtField = new javax.swing.JTextField();
        OutputLbl = new javax.swing.JLabel();
        CipherSelectBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleLbl.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TitleLbl.setText("Text Encryptor / Decryptor");

        InputTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTxtFieldActionPerformed(evt);
            }
        });

        InputLbl.setText("Text to encrypt / decrypt");

        EncryptBtn.setText("Encrypt Text");
        EncryptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncryptBtnActionPerformed(evt);
            }
        });

        DecryptBtn.setText("Decrypt Text");
        DecryptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecryptBtnActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        KeyLbl.setText("Key");

        OutputTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutputTxtFieldActionPerformed(evt);
            }
        });

        OutputLbl.setText("Output Text");

        CipherSelectBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Cipher", "Caesar", "Rail Fence", "Numerical", "Veneer" }));
        CipherSelectBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CipherSelectBoxItemStateChanged(evt);
            }
        });
        CipherSelectBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CipherSelectBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TitleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InputLbl)
                    .addComponent(InputTxtField)
                    .addComponent(KeyLbl)
                    .addComponent(jTextField2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OutputTxtField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(OutputLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EncryptBtn)
                                .addGap(18, 18, 18)
                                .addComponent(DecryptBtn)
                                .addGap(18, 18, 18)
                                .addComponent(CipherSelectBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(47, 47, 47)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLbl)
                .addGap(18, 18, 18)
                .addComponent(InputLbl)
                .addGap(18, 18, 18)
                .addComponent(InputTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(KeyLbl)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EncryptBtn)
                    .addComponent(DecryptBtn)
                    .addComponent(CipherSelectBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(OutputLbl)
                .addGap(18, 18, 18)
                .addComponent(OutputTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EncryptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncryptBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EncryptBtnActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void InputTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputTxtFieldActionPerformed

    private void DecryptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecryptBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DecryptBtnActionPerformed

    private void OutputTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutputTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OutputTxtFieldActionPerformed

    private void CipherSelectBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CipherSelectBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CipherSelectBoxActionPerformed

    private void CipherSelectBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CipherSelectBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CipherSelectBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CipherPanel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CipherSelectBox;
    private javax.swing.JButton DecryptBtn;
    private javax.swing.JButton EncryptBtn;
    private javax.swing.JLabel InputLbl;
    private javax.swing.JTextField InputTxtField;
    private javax.swing.JLabel KeyLbl;
    private javax.swing.JLabel OutputLbl;
    private javax.swing.JTextField OutputTxtField;
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
